### ISSUE TITLE
Error when accessing Store > Configuration > Sales > Payment Methods

### ISSUE THREAD

**Issue by kartguru** [fontis/australia-mage2#3]
Hi

I'm finding that Magento v2.1.6 is throwing these errors when I try to access Store > Configuration > Sales > Payment Methods in Admin.

main.CRITICAL: Recoverable Error: Argument 1 passed to Fontis\CustomerGroupAccess\Source\CustomerGroup::__construct() must implement interface Magento\Customer\Api\GroupManagementInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /public_html/vendor/fontis/customergroupaccess-mage2/src/Source/CustomerGroup.php on line 42 [] []

Thanks in advance for looking into this.

- michael

**Comment by chnorton** [comment]
From memory this is something to do with the DI compilation not having been updated/re-run, so Magento passes through a generic ObjectManager rather than an instance with the interface you expect. I'll take a look at it and see if I can get you more specific information about how to solve it.

**Comment by chnorton** [comment]
OK, so the issue is with the fontis/customergroupaccess-mage2 library not being a "proper" Magento 2 library so it wasn't working with the DI system as you'd expect. This was fine in dev mode, but production mode doesn't compile it properly and causes the error you're seeing. The customergroupaccess-mage2 library has been updated to version 1.0.1 now, so updating to that version should resolve this.

Hopefully it's a simple `composer update fontis/customergroupaccess-mage2` away!
